version: '3.9'

services:
  djangoapp:
    build: .
    command: ./entrypoint.sh
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    image: postgres:16-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - djangoapp
