services:

  djangoapp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: djangoapp

    command: gunicorn dossie_caixa.wsgi:application --bind 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - ./djangoapp:/djangoapp
      - static_volume:/data/web/static

    env_file:
      - ./dotenv_files/.env

    depends_on:
      - psql

    networks:
      - backend

  psql:
    image: postgres:16

    container_name: psql

    restart: always

    environment:
      POSTGRES_DB: dossie_caixa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dossie2026

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - backend

  nginx:
    image: nginx:1.29

    container_name: nginx

    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/data/web/static

    depends_on:
      - djangoapp

    networks:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
  frontend:
